package com.hm.geek.beauty.design.ch34_ch37.refactor4;

import com.google.common.annotations.VisibleForTesting;
import com.hm.geek.beauty.design.ch34_ch37.refactor1.LogTraceIdGenerator;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Id Generator that is used to generate random IDs.
 *
 * <p>
 * The IDs generated by this class are not absolutely unique,
 * but the probability of duplication is very low.
 */
@SuppressWarnings("all")
public class RandomIdGenerator implements LogTraceIdGenerator {
    private static final Logger logger = LoggerFactory.getLogger(RandomIdGenerator.class);

    /**
     * Generate the random ID. The IDs may be duplicated only in extreme situation.
     *
     * @return a random ID
     */
    @Override
    public String generate() {
        //...
        return "";
    }

    /**
     * Get the local hostname and
     * extract the last field of the name string split by delimiter '.'.
     *
     * @return the last field of hostname. Returns null if hostname is not obtained.
     */
    private String getLastFieldOfHostName() {
        //...
        return "";
    }

    /**
     * Get the last field of {@hostName} split by delimiter '.'.
     *
     * @param hostName should not be null
     * @return the last field of {@hostName}. Returns empty string if {@hostName} is empty string.
     */
    @VisibleForTesting
    protected String getLastSubstrSplitByDot(String hostName) {
        //...
        return "";
    }

    /**
     * Generate random string which
     * only contains digits, uppercase letters and lowercase letters.
     *
     * @param length should not be less than 0
     * @return the random string. Returns empty string if {@length} is 0
     */
    @VisibleForTesting
    protected String generateRandomAlphameric(int length) {
        //...
      return "";
    }
}